downgrade edgetpu-compiler to be 14.1
knorth55/coral_usb_ros pull request #78
Opened 2022-01-20 09:01 UTC by fanshi14

`edgetpu-compiler` `14.1` instead of latest `16.0` [from debian](https://github.com/knorth55/coral_usb_ros/blob/master/training/labelme_voc/Dockerfile#L70) is forced to be installed, reasons are:
- If using `16.0`, loading tpu model file with `coral_usb_ros` will fail with output `RuntimeError: Failed to prepare for TPU. Failed precondition: Package requires runtime version (14), which is newer than this runtime version (13).Node number 0 (edgetpu-custom-op) failed to prepare` as [this instruction](https://coral.ai/docs/edgetpu/compiler/#compiler-and-runtime-versions).
- Tpu model file from `16.0` compiler requires [runtime 14](https://coral.ai/docs/edgetpu/compiler/#compiler-and-runtime-versions), however [runtime installation](https://github.com/knorth55/coral_usb_ros#install-the-edge-tpu-runtime) in `coral_usb_ros`  with [deprecated](https://coral.ai/software/#debian-packages) `python3-edgetpu` only supports runtime 13.
- `edgetpu-compiler` being `14.1` in the previous dlbox3 image works without problem, therefore we choose `14.1` instead of `15.0`.

The modification has been verified with `labelme_voc` demo without problem.

2022-01-20 09:11 UTC, knorth55 commented
Super!

2022-01-20 09:29 UTC, knorth55 requested changes

2022-01-20 09:29 UTC, knorth55 commented on training/epic_kitchens_55/Dockerfile
> +RUN gdown https://drive.google.com/uc?id=1vgy3vTqhfQ5kedQLF1NzegDbw25LbAkb && \
how about `https://packages.cloud.google.com/apt/pool/libedgetpu1_14.1_amd64_ef6eef29200270dcb941d2c1defa39c7d80e9c6f30cf7ced1c653a30bde0a502.deb`?

2022-01-20 09:34 UTC, knorth55 commented on training/epic_kitchens_55/Dockerfile
> +RUN gdown https://drive.google.com/uc?id=1vgy3vTqhfQ5kedQLF1NzegDbw25LbAkb && \
can you also check `libedgetpu1-legacy-std` with `edgetpu_compiler` `16.0`?
https://github.com/knorth55/coral_usb_ros#install-the-edge-tpu-runtime

2022-01-20 10:29 UTC, fanshi14 commented on training/epic_kitchens_55/Dockerfile
> +RUN gdown https://drive.google.com/uc?id=1vgy3vTqhfQ5kedQLF1NzegDbw25LbAkb && \
> how about `https://packages.cloud.google.com/apt/pool/libedgetpu1_14.1_amd64_ef6eef29200270dcb941d2c1defa39c7d80e9c6f30cf7ced1c653a30bde0a502.deb`?

Thanks for the advice! Could you tell me how do you find it? Actually we need `libedgetpu1-std_14.1` instead of `libedgetpu1_14.1`, I will update when I get the link.

2022-01-20 10:48 UTC, fanshi14 commented on training/epic_kitchens_55/Dockerfile
> +RUN gdown https://drive.google.com/uc?id=1vgy3vTqhfQ5kedQLF1NzegDbw25LbAkb && \
> libedgetpu1-legacy-std

I tried to install `libedgetpu1-legacy-std` with `edgetpu_compiler` `16.0`, but it does not work.
Also when `edgetpu_compiler` is `16.0`, it even does not require `libedgetpu1-std`.
So I think we have to downgrade `edgetpu_compiler`.

2022-01-21 04:31 UTC, knorth55 commented on training/epic_kitchens_55/Dockerfile
> +RUN gdown https://drive.google.com/uc?id=1vgy3vTqhfQ5kedQLF1NzegDbw25LbAkb && \
I just used the same sha25 key as `edgetpu_compiler` and I can get the deb file.
```
https://packages.cloud.google.com/apt/pool/libedgetpu1-std_14.1_amd64_ef6eef29200270dcb941d2c1defa39c7d80e9c6f30cf7ced1c653a30bde0a502.deb
```
this can be also downlodable, too.

2022-01-21 04:35 UTC, knorth55 commented on training/epic_kitchens_55/Dockerfile
> +RUN gdown https://drive.google.com/uc?id=1vgy3vTqhfQ5kedQLF1NzegDbw25LbAkb && \
`https://packages.cloud.google.com/apt/pool/libedgetpu1-std_14.1_amd64_4669a44bd6d6f3b7d33c356182ceaeb29e1c981843629adeb77ac1283dbd498e.deb`
this is also donwloadable...

2022-01-21 10:16 UTC, fanshi14 commented on training/epic_kitchens_55/Dockerfile
> +RUN gdown https://drive.google.com/uc?id=1vgy3vTqhfQ5kedQLF1NzegDbw25LbAkb && \
I'm afraid the link of `libedgetpu1-std` is not correct.
Actually `https://packages.cloud.google.com/apt/pool/libedgetpu1-std_14.1_amd64_ef6eef29200270dcb941d2c1defa39c7d80e9c6f30cf7ced1c653a30bde0a502.deb` is still `edgetpu-compiler`, because both deb files are in the same size (6.16 Mb). So I guess the sha25 key decides the identical file?

`https://packages.cloud.google.com/apt/pool/libedgetpu1-std_14.1_amd64_4669a44bd6d6f3b7d33c356182ceaeb29e1c981843629adeb77ac1283dbd498e.deb` is in `arm64` version, it will output the error during docker build: ` package architecture (arm64) does not match system (amd64)`.

Do you have any hint about how to find it? I googled a lot but found nothing related.

2022-01-22 03:17 UTC, knorth55 commented on training/epic_kitchens_55/Dockerfile
> +RUN gdown https://drive.google.com/uc?id=1vgy3vTqhfQ5kedQLF1NzegDbw25LbAkb && \
i searched on github

2022-01-22 03:26 UTC, knorth55 commented on training/epic_kitchens_55/Dockerfile
> +RUN gdown https://drive.google.com/uc?id=1vgy3vTqhfQ5kedQLF1NzegDbw25LbAkb && \
```
apt-get -y install --print-uris libedgetpu1-std=14.1 | cut -f 2 -d \' | grep \.deb
```

you can get the url from this command, but my apt forgot `14.1` already.
I will merge this PR.

2022-01-22 03:27 UTC, knorth55 approved these changes

2022-01-22 03:27 UTC, merged

2022-01-22 05:24 UTC, fanshi14 commented on training/epic_kitchens_55/Dockerfile
> +RUN gdown https://drive.google.com/uc?id=1vgy3vTqhfQ5kedQLF1NzegDbw25LbAkb && \
That's very helpful, thanks! I obtained the link from previous docker image in dlbox3.